trigger:
  - main
  - milestones/*

pool: "DW10"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "20.x"
    displayName: "Install Node.js"

  - script: |
      npm install
    displayName: "npm install"

  - script: |
      npm run build --verbose
    displayName: "npm run build"

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "$(Build.SourcesDirectory)/Files"
      includeRootFolder: false
      archiveType: "zip"
      archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "swift-v2"
      publishLocation: "Container"
    displayName: "Publish artifact"
  
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        Write-Host '- - - - - - - - - - - - - - - - - - - - - - - - -'
        Write-Host ' Get swift version from package.json'
        Write-Host '- - - - - - - - - - - - - - - - - - - - - - - - -'
        $versionString=$(node -p "require('./package.json').version") 
            echo "##vso[task.setvariable variable=swiftVersion;isOutput=true]$versionString"
