name: deploy uat
on:  
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  upload:
    runs-on: ubuntu-latest
    environment: 
      name: UAT
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install
      - name: Build for UAT
        run: npm run build:webpack

      - uses: azure/login@v1
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to storage using CLI
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            ls
            # az storage account upload
            az storage file upload-batch --account-key ${{ secrets.ACCOUNT_KEY}} --account-name ${{ secrets.ACCOUNT_NAME}} --destination ${{ secrets.SHARE_NAME }} --source '${{ env.SOURCE_DIR }}' --destination-path '${{ env.DEST_DIR }}''
