name: deploy prod
on:
  workflow_dispatch:
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Dependencies
        run: npm install
      - name: Build for UAT
        run: npm run build:webpack

      - uses: azure/login@v1
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: cahaseler/azure-fileshare-upload@v1.0.0
        with:
          account_name: ${{ secrets.ACCOUNT_NAME }}
          account_key: ${{ secrets.ACCOUNT_KEY}}
          share_name: ${{ secrets.SHARE_NAME }}
          source_dir: ${{ secrets.SOURCE_DIR }}
